# Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: false
    fetch-registry: true
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Datasource properties
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/docker-test
    username: postgres
    password: postgres


spring.jpa:
  hibernate:
    ddl-auto: create

# JWT properties
jwt:
  secret: MartinSecretKeyToGenJWTs
  expirationTime: 864_000_000 # 10 days
  tokenPrefix: "Bearer "
  headerString: Authorization