# Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: false
    fetch-registry: true
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Zuul proxy config
zuul:
  ignored-services: '*'
  routes:
    gateway: /gateway/**

management:
  security:
    enabled: false